version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - "./data/app/config:/var/www/html/config:ro"
      - "./data/app/upload:/var/www/html/upload"
      - "./data/app/logs:/var/www/html/logs"

    depends_on: 
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - "./data/pgdata:/var/lib/postgresql/data"
      - "./pgsqldb:/scripts:ro"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/nginx/config:/etc/nginx/conf.d/sites:ro"
      - "./data/nginx/cert:/etc/nginx/ssl/cert:ro"
      - "./data/nginx/acme:/acme:ro"
      - "./www:/var/www/html:ro"

  acme:
    image: neilpang/acme.sh
    volumes:
      - "./data/acme:/acme.sh"
      - "./data/nginx/cert:/cert"
      - "./data/nginx/acme:/html"
